### ISSUE TITLE
Aura 1.x release

### ISSUE THREAD

**Issue by harikt** [auraphp/bin#7]
Hi Paul, 

I did a Aura.Input 1.2.0 release.

I don't know how the auraphp.com shows the latest version. Do we need to manually update those?

Currently I have manually made the change to package.json file.

Thank you.

**Comment by pmjones** [comment]
Dude, sweet! This is great news. :-)

To update the site:

- Clone the site locally on your machine.

- In the aura-bin env file, set `AURA_BIN_SITE_DIR=/path/to/local/site/checkout`.

- You can then issue `aura packages-json Aura.Input`, and it will update packages.json for you with the Aura.Input release. (If you don't specify a package, it will do it for all packages, which is pretty slow.)

- Then commit and push the site.

Let me know if that helps or not!

**Comment by harikt** [comment]
Yes, thanks that was very helpful.
